
from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "L0iFQrmhaqpL0Dc1W8vwrFc8"

CLOUD_ID = "kookdata:YXAtbm9ydGhlYXN0LTIuYXdzLmVsYXN0aWMtY2xvdWQuY29tOjkyNDMkZjhmY2IzMDdhNmY1NDcxYTgxOGZiYjljZTlhN2NkY2IkNmZiNzg5Yzg1YmIzNGFhNmFiNjQ5OTYzMzdmNGYzZDA="
# Create the client instance
client = Elasticsearch(
    #hosts=["https://kookdata.kb.ap-northeast-2.aws.elastic-cloud.com:9243"],
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

def createIndex(client):
    client.indices.create(
        index = "current_location",
        body = {
            "settings" : {
                "number_of_shards": 1
            },
            "mappings" : {
                "properties" : {
                    "current_loc" : {"type":"geo_point"}
                }
            }
        }
    )

def dataInsert(client, data):
    doc= {
        "current_loc" : [data["longitude"], data["latitude"]]
    }
    res = client.index(index="current_location", id=2, body=doc)
    print(res)

# createIndex(client)
# dataInsert(client, x)
# Successful response!
# print(client.info())
